apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  labels:
    app: ic-webapp
    env: prod
  namespace: ic-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
        - image: sadokkhemila/ic-webapp:1.0
          name: ic-webapp

          ports:
            - containerPort: 8080
              name: ic-webapp
