apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-configmap
  namespace: api-webapp
  labels:
    env: prod

data:
  servers.json: |
    {
      "Servers": {
             "1": {
                "Name": "Minimally Defined Server",
                "Group": "Server Group 1",
                "Port": 5432,
                "Username": "postgres",
                "Host": "localhost",
                "SSLMode": "prefer",
                "MaintenanceDB": "postgres"
            }
          }
    }
