apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-admin
  labels:
    app: pg-admin
    env: prod
  namespace: ic-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-admin
  template:
    metadata:
      labels:
        app: pg-admin
    spec:
      containers:
        - image: dpage/pgadmin4
          name: pg-admin
          env:
            - name: USER_EMAIL
              value: pgadmin@pgadmin.com
            - name: PGADMIN_PAWSSORD
              valueFrom:
                secretKeyRef:
                  name: pg-admin
                  key: PGADMIN_PASSWORD
          ports:
            - containerPort: 5050
              name: postgres
          volumeMounts:
            - name: pg-admin-server
              mountPath: /pgadmin4
            - name: pg-admin-data
              mouthPath: /var/lib/pgadmin

      volumes:
        - name: pg-admin-server
          ConfigMap:
            name: special-config
            items:
              - key: servers.json
                path: servers.json
        - name: pg-admin-data
          persistentVolumeClaim:
            claimName: pgadmin-vpc
