apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
    env: prod
  namespace: ic-webapp
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - port: 5050
      targetPort: 80
      nodePort: 30050
      protocol: TCP
