apiVersion: v1
data:
  servers.json: |
    {
      "Servers":
        {
          "1":
            {
              "Name": "docker_postgres",
              "Group": "docker_postgres_group",
              "Port": 5432,
              "Username": "odoo_user",
              "Host": "postgres",
              "SSLMode": "prefer",
              "MaintenanceDB": "postgres"
            }
        }
    }
kind: ConfigMap
metadata:
  name: pgadmin-configmap
  namespace: ic-webapp
  labels:
    env: prod
