apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-pv
  labels:
    type: local
    env: prod
  namespace: ic-webapp
spec:
  capacity:
    storage: 20Gi

  accessModes:
    - ReadWriteMany

  storageClassName: manual
  hostpath:
    path: "/data_k8s/lib-odoo"
