apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    env: prod
  namespace: ic-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:10
          name: postgres
          env:
            - name: POSTGRES-DB
              value: postgres
            - name: POSTGRES-USER
              value: toto
            - name: POSTGRES_PAWSSORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD

          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
          volumes:
            - name: pg-data
              hostpath:
                 path: /data_k8s/postgres
