apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    env: prod
  namespace: ic-webapp
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
